#!/bin/sh

# Update the symlink to the ssh agent socket whenever ssh is used
# so tmux panes always use a valid socket.
#
# Idea comes from https://werat.dev/blog/happy-ssh-agent-forwarding/
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
