# Bashrc extension for custom configs
# Should be sourced at the end of .bashrc

# ===[ PATH exports for tools ]===

export PATH="/usr/local/texlive/2023/bin/x86_64-linux:$PATH"


# ===[ Powerline ]===

# Run powerline daemon
powerline-daemon -q
# To locate this directory, run: pip show powerline-status
# export POWERLINE_LOCATION="$(pip show powerline-status | sed -rn 's|^Location: (.*)$|\1|p')/powerline"
export POWERLINE_LOCATION="$HOME/.local/lib/python3.10/site-packages/powerline"
export POWERLINE_CONFIG_COMMAND=powerline-config
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
# Invoke binding script
. "$POWERLINE_LOCATION/bindings/bash/powerline.sh"


# ===[ Aliases ]===

alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dotfiles_tig='tig -C$HOME/.dotfiles/'

alias r='. ranger'
alias fd=fdfind

alias gs='git status'
alias gch='git checkout'
alias ga='git add'
alias gco='git commit'
alias gcoa='git commit --amend'
alias gcp='git cherry-pick'
alias gri='git rebase -i --autosquash'
alias tiga='tig --all'

# Generate .pdf files for all .adoc files found recursively from the current directory
alias asciidoctor-pdf-recursive='for f in $(find . -name "*.adoc"); do asciidoctor-pdf --q $f 2> /dev/null; done'

# USB Serial ports
alias p0='picocom -b 115200 /dev/ttyUSB0'
alias p1='picocom -b 115200 /dev/ttyUSB1'
